title = "Swift You and I"
baseURL = "https://swiftui.diegolavalle.com/"
languageCode = "en-us"
disableKinds = ["RSS"]
enableInlineShortcodes = true

[taxonomies]
tag = "tags"

[outputs]
section = ["HTML", "JSON"]
page = ["HTML", "JSON"]
taxonomyTerm = ["HTML", "JSON"]

[params]
  subtitle = "A blog about SwiftUI and related Apple ecosystem technologies"
  appLink = "https://apps.apple.com/app/working-examples-for-swiftui/id1566337950"

[markup]
[markup.highlight]
  codeFences = false
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "tango"
  tabWidth = 2
