[build]
publish = "www"
command = "swift run -c release SwiftySitesWebsite --clean"

[[redirects]]
from = "/swiftysites.doccarchive/documentation/"
to = "/swiftysites.doccarchive/documentation/root/"

[[redirects]]
from = "/swiftysites.doccarchive/"
to = "/swiftysites.doccarchive/documentation/root/"

[[redirects]]
from = "/gfmarkdown.doccarchive/documentation/"
to = "/gfmarkdown.doccarchive/documentation/gfmarkdown/"

[[redirects]]
from = "/gfmarkdown.doccarchive/"
to = "/gfmarkdown.doccarchive/documentation/gfmarkdown/"
