[build]
#base = ""
publish = "www"
command = "echo"

[[redirects]]
from = "/documentation/*"
status = 200
to = "/SwiftySites.doccarchive/index.html"

[[redirects]]
from = "/tutorials/*"
status = 200
to = "/SwiftySites.doccarchive/index.html"

[[redirects]]
from = "/data/documentation.json"
status = 200
to = "/SwiftySites.doccarchive/data/documentation/root.json"

[[redirects]]
from = "/css/*"
status = 200
to = "/SwiftySites.doccarchive/css/:splat"

[[redirects]]
from = "/data/*"
status = 200
to = "/SwiftySites.doccarchive/data/:splat"

[[redirects]]
from = "/downloads/*"
status = 200
to = "/SwiftySites.doccarchive/downloads/:splat"

[[redirects]]
from = "/images/*"
status = 200
to = "/SwiftySites.doccarchive/images/:splat"

[[redirects]]
from = "/img/*"
status = 200
to = "/SwiftySites.doccarchive/img/:splat"

[[redirects]]
from = "/index/*"
status = 200
to = "/SwiftySites.doccarchive/index/:splat"

[[redirects]]
from = "/js/*"
status = 200
to = "/SwiftySites.doccarchive/js/:splat"

[[redirects]]
from = "/videos/*"
status = 200
to = "/SwiftySites.doccarchive/videos/:splat"

[[redirects]]
from = "/metadata.json"
status = 200
to = "/SwiftySites.doccarchive/metadata.json"

[[redirects]]
from = "/theme-settings.json"
status = 200
to = "/SwiftySites.doccarchive/theme-settings.json"
